#ifndef HPKNXD_KNX_HEADER_H
#define HPKNXD_KNX_HEADER_H

#include "../msgbuilder.h"

/**
 * KNXnet/IP Service Type
 */
typedef enum {
	KNXNETIP_SEARCH_REQUEST,
	KNXNETIP_SEARCH_RESPONSE,
	KNXNETIP_DESCRIPTION_REQUEST,
	KNXNETIP_DESCRIPTION_RESPONSE,
	KNXNETIP_CONNECTION_REQUEST,
	KNXNETIP_CONNECTION_RESPONSE,
	KNXNETIP_CONNECTIONSTATE_REQUEST,
	KNXNETIP_CONNECTIONSTATE_RESPONSE,
	KNXNETIP_DISCONNECT_REQUEST,
	KNXNETIP_DISCONNECT_RESPONSE,
	KNXNETIP_DEVICE_CONFIGURATION_REQUEST,
	KNXNETIP_DEVICE_CONFIGURATION_ACK,
	KNXNETIP_TUNNEL_REQUEST,
	KNXNETIP_TUNNEL_RESPONSE,
	KNXNETIP_ROUTING_INDICATION
} knxnetip_service;

/**
 * Append a KNXnet/IP header which advocates the given service and payload length.
 */
bool knxnetip_append_header(msgbuilder* mb, knxnetip_service srv, uint16_t length);

#endif
